import java.io.*;
import java.awt.Image;
import java.net.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import java.io.File;

public class WeatherAppGUI extends javax.swing.JFrame {
    
    private final DefaultTableModel model;
    private static final String DEFAULT_COMBO_TEXT = "Pilih kota favorit...";
    private boolean sedangMemuatFavorit;
    
    public WeatherAppGUI() {
    initComponents();

    // SQLite
    DatabaseManager.createTable();
    loadFavoritKeComboBox();

    // Inisialisasi tabel
    model = (DefaultTableModel) tblCuaca.getModel();
    model.setRowCount(0);

    // Non-editable fields
    txtKelembapan.setEditable(false);
    txtKecepatanAngin.setEditable(false);
    txtTekanan.setEditable(false);

    // Event Handler: Tambah Favorit (SQLite)
    btnTambahFavorit.addActionListener(e -> {
        String kota = txtNamaKota.getText().trim();
        if (!kota.isEmpty()) {
            DatabaseManager.tambahFavorit(kota);
            loadFavoritKeComboBox();
            JOptionPane.showMessageDialog(this, kota + " ditambahkan ke favorit!");
        } else {
            JOptionPane.showMessageDialog(this, "Masukkan kota valid!");
        }
    });

    // Event Handler: Hapus Favorit (SQLite)
    btnHapusFavorit.addActionListener(e -> {
        String selectedCity = (String) cbmbxFavorit.getSelectedItem();
        if (selectedCity != null && !selectedCity.equals(DEFAULT_COMBO_TEXT)) {
            DatabaseManager.hapusFavorit(selectedCity);
            loadFavoritKeComboBox();
            JOptionPane.showMessageDialog(this, selectedCity + " dihapus!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih kota dari favorit!");
        }
    });

    // vent Handler: Pilih dari Favorit
    cbmbxFavorit.addActionListener(e -> {
    if (sedangMemuatFavorit) return; // ⛔ Jangan jalankan saat update ComboBox

    String selectedCity = (String) cbmbxFavorit.getSelectedItem();
    if (selectedCity != null && !selectedCity.equals(DEFAULT_COMBO_TEXT)) {
        txtNamaKota.setText(selectedCity);
        cekCuaca(selectedCity);
    }
});

    // CSV & Riwayat
    btnSimpan.addActionListener(e -> simpanCSV());
    btnHapus.addActionListener(e -> hapusRiwayat());

    resetTampilan();
}
    
    
    /*
    public WeatherAppGUI(javax.swing.table.DefaultTableModel model) {
        this.model = model;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AplikasiCekCuaca = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNamaKota = new javax.swing.JTextField();
        cbmbxFavorit = new javax.swing.JComboBox<>();
        lblAtau = new javax.swing.JLabel();
        btnCekCuaca = new javax.swing.JButton();
        btnTambahFavorit = new javax.swing.JButton();
        btnHapusFavorit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblInformasiCuaca = new javax.swing.JLabel();
        lblNamaKota = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblKondisiCuaca = new javax.swing.JLabel();
        lbliconCuaca = new javax.swing.JLabel();
        txtKelembapan = new javax.swing.JTextField();
        txtKecepatanAngin = new javax.swing.JTextField();
        txtTekanan = new javax.swing.JTextField();
        lblRiwayatPencarian = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuaca = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(11, 166, 223));

        AplikasiCekCuaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AplikasiCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        AplikasiCekCuaca.setText("APLIKASI CEK CUACA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(AplikasiCekCuaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AplikasiCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(203, 220, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukkan Nama Kota:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        cbmbxFavorit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAtau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtau.setText("Atau");

        btnCekCuaca.setBackground(new java.awt.Color(99, 163, 97));
        btnCekCuaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        btnCekCuaca.setText("Cek Cuaca");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnTambahFavorit.setBackground(new java.awt.Color(248, 123, 27));
        btnTambahFavorit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahFavorit.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahFavorit.setText("Tambah Favorit");
        btnTambahFavorit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahFavoritActionPerformed(evt);
            }
        });

        btnHapusFavorit.setBackground(new java.awt.Color(205, 44, 88));
        btnHapusFavorit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusFavorit.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusFavorit.setText("Hapus Favorit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambahFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusFavorit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAtau)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmbxFavorit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmbxFavorit)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAtau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahFavorit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(140, 205, 235));

        lblInformasiCuaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInformasiCuaca.setText("Informasi Cuaca");

        lblSuhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbliconCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKondisiCuaca)
                            .addComponent(lblNamaKota)
                            .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblInformasiCuaca)
                        .addGap(218, 218, 218))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformasiCuaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbliconCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblKondisiCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtKelembapan.setText("Kelembapan:");

        txtKecepatanAngin.setText("Kec. Angin:");

        txtTekanan.setText("Tekanan:");

        lblRiwayatPencarian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRiwayatPencarian.setText("Riwayat Pencarian:");

        tblCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kota", "Suhu", "Kondisi", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(tblCuaca);

        btnSimpan.setBackground(new java.awt.Color(84, 89, 172));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan ke CSV");

        btnHapus.setBackground(new java.awt.Color(221, 168, 83));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Riwayat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRiwayatPencarian)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtKecepatanAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtTekanan, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKecepatanAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTekanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRiwayatPencarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
        String kota = txtNamaKota.getText().trim();
    if (!kota.isEmpty()) {
        cekCuaca(kota);
    } else {
        JOptionPane.showMessageDialog(this, "Masukkan nama kota.");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    private void btnTambahFavoritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahFavoritActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahFavoritActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new WeatherAppGUI().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AplikasiCekCuaca;
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusFavorit;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahFavorit;
    private javax.swing.JComboBox<String> cbmbxFavorit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtau;
    private javax.swing.JLabel lblInformasiCuaca;
    private javax.swing.JLabel lblKondisiCuaca;
    private javax.swing.JLabel lblNamaKota;
    private javax.swing.JLabel lblRiwayatPencarian;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lbliconCuaca;
    private javax.swing.JTable tblCuaca;
    private javax.swing.JTextField txtKecepatanAngin;
    private javax.swing.JTextField txtKelembapan;
    private javax.swing.JTextField txtNamaKota;
    private javax.swing.JTextField txtTekanan;
    // End of variables declaration//GEN-END:variables

    private void cekCuaca(String kota) {
        try {
            WeatherAPI.WeatherData data = WeatherAPI.getWeather(kota);

            lblNamaKota.setText(data.getKotaNegara());
            lblSuhu.setText(data.getSuhu() + "°C");
            lblKondisiCuaca.setText(data.getKondisi());

            txtKelembapan.setText("Kelembapan: " + data.getKelembapan() + "%");
            txtTekanan.setText("Tekanan: " + data.getTekanan() + " hPa");
            txtKecepatanAngin.setText("Kec. Angin: " + data.getAnginKMH() + " km/h");

            tampilkanIcon(data.getIconCode());

            model.addRow(new Object[]{
                data.getKotaNegara(),
                data.getSuhu() + "°C",
                data.getKondisi(),
                java.time.LocalDateTime.now().toString()
            });

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data cuaca: " + ex.getMessage());
            resetTampilan();
        }
    }

    private void loadFavoritKeComboBox() {
    sedangMemuatFavorit = true; // memblokir event ComboBox sementara
    cbmbxFavorit.removeAllItems();
    cbmbxFavorit.addItem(DEFAULT_COMBO_TEXT);

    for (String kota : DatabaseManager.getFavorit()) {
        cbmbxFavorit.addItem(kota);
    }
    sedangMemuatFavorit = false; // mengaktifkan kembali event
}

    private void resetTampilan() {
        lblNamaKota.setText("-");
        lblSuhu.setText("- °C");
        lblKondisiCuaca.setText("-");
        txtKelembapan.setText("Kelembapan: -");
        txtTekanan.setText("Tekanan: -");
        txtKecepatanAngin.setText("Kec. Angin: -");

        if (lbliconCuaca != null) {
            lbliconCuaca.setIcon(null);
            lbliconCuaca.setText("Icon");
        }
    }

    private void tampilkanIcon(String iconCode) {
        try {
            URL url = new URL("https://openweathermap.org/img/wn/" + iconCode + "@2x.png");
            ImageIcon icon = new ImageIcon(url);
            Image scaled = icon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
            lbliconCuaca.setIcon(new ImageIcon(scaled));
            lbliconCuaca.setText(null);
        } catch (Exception e) {
            lbliconCuaca.setText("Error");
        }
    }

    private void simpanCSV() {
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new File("riwayat_cuaca.csv"));

        if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

        File file = chooser.getSelectedFile();
        if (!file.getName().toLowerCase().endsWith(".csv")) {
            file = new File(file.getAbsolutePath() + ".csv");
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println("Kota,Suhu,Kondisi,Waktu");

            for (int i = 0; i < model.getRowCount(); i++) {
                pw.println(
                    model.getValueAt(i,0)+","+
                    model.getValueAt(i,1)+","+
                    model.getValueAt(i,2)+","+
                    model.getValueAt(i,3)
                );
            }
            JOptionPane.showMessageDialog(this, "Berhasil disimpan!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan CSV.");
        }
    }

    private void hapusRiwayat() {
        model.setRowCount(0);
    JOptionPane.showMessageDialog(this, "Riwayat dihapus.");
    }
}