import java.io.*;
import java.awt.Image;
import java.net.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.json.JSONException;

public class WeatherAppGUI extends javax.swing.JFrame {
    // model tabel (ambil dari tblCuaca setelah initComponents)
    private DefaultTableModel model;
   
    public WeatherAppGUI() {
        initComponents();
        // Ambil model dari JTable desain NetBeans & kosongkan
        model = (DefaultTableModel) tblCuaca.getModel();
        model.setRowCount(0);

        // Jadikan badge non-editable
        txtKelembapan.setEditable(false);
        txtKecepatanAngin.setEditable(false);
        txtTekanan.setEditable(false);

        // Default combo box
        cbmbxFavorit.removeAllItems();
        cbmbxFavorit.addItem("Pilih kota favorit...");

        // Tombol / event
        btnCekCuaca.addActionListener(e -> {
            String kota = txtNamaKota.getText().trim();
            if (!kota.isEmpty()) cekCuaca(kota);
            else JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu.");
        });

        btnTambahFavorit.addActionListener(e -> {
            String kota = txtNamaKota.getText().trim();
            if (!kota.isEmpty() && !kota.equals("Pilih kota favorit...")) {
                // hindari duplikat
                boolean exists = false;
                for (int i = 0; i < cbmbxFavorit.getItemCount(); i++) {
                    if (kota.equalsIgnoreCase(cbmbxFavorit.getItemAt(i))) { exists = true; break; }
                }
                if (!exists) cbmbxFavorit.addItem(kota);
                JOptionPane.showMessageDialog(this, "Kota " + kota + " ditambahkan ke favorit!");
            } else {
                JOptionPane.showMessageDialog(this, "Masukkan nama kota terlebih dahulu.");
            }
        });

        btnHapusFavorit.addActionListener(e -> {
            Object sel = cbmbxFavorit.getSelectedItem();
            if (sel != null && !sel.equals("Pilih kota favorit...")) {
                cbmbxFavorit.removeItem(sel);
                JOptionPane.showMessageDialog(this, "Favorit dihapus.");
            } else {
                JOptionPane.showMessageDialog(this, "Pilih favorit yang ingin dihapus.");
            }
        });

        cbmbxFavorit.addItemListener(e -> {
            if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                String kota = (String) e.getItem();
                if (!"Pilih kota favorit...".equals(kota)) {
                    txtNamaKota.setText(kota);
                    cekCuaca(kota);
                }
            }
        });

        btnSimpan.addActionListener(e -> simpanCSV());
        btnMuatData.addActionListener(e -> muatCSV());
        btnHapus.addActionListener(e -> {
            if (model.getRowCount() > 0) {
                model.setRowCount(0);
                JOptionPane.showMessageDialog(this, "Riwayat telah dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Riwayat kosong.");
            }
        });
        
        lblInformasiCuaca.setHorizontalAlignment(SwingConstants.CENTER);
        lblNamaKota.setHorizontalAlignment(SwingConstants.CENTER);
        lblSuhu.setHorizontalAlignment(SwingConstants.CENTER);
        lblKondisiCuaca.setHorizontalAlignment(SwingConstants.CENTER);
        lblSuhu.setFont(lblSuhu.getFont().deriveFont(32f));
        lblNamaKota.setFont(lblNamaKota.getFont().deriveFont(16f));
        lblKondisiCuaca.setFont(lblKondisiCuaca.getFont().deriveFont(14f));
        // Trik: taruh ikon di label kota dan teks di bawah ikon
        lblNamaKota.setHorizontalTextPosition(SwingConstants.CENTER);
        lblNamaKota.setVerticalTextPosition(SwingConstants.BOTTOM);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AplikasiCekCuaca = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtNamaKota = new javax.swing.JTextField();
        cbmbxFavorit = new javax.swing.JComboBox<>();
        lblAtau = new javax.swing.JLabel();
        btnCekCuaca = new javax.swing.JButton();
        btnTambahFavorit = new javax.swing.JButton();
        btnHapusFavorit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblInformasiCuaca = new javax.swing.JLabel();
        lblNamaKota = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        lblKondisiCuaca = new javax.swing.JLabel();
        txtKelembapan = new javax.swing.JTextField();
        txtKecepatanAngin = new javax.swing.JTextField();
        txtTekanan = new javax.swing.JTextField();
        lblRiwayatPencarian = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCuaca = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnMuatData = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(11, 166, 223));

        AplikasiCekCuaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AplikasiCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        AplikasiCekCuaca.setText("APLIKASI CEK CUACA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(AplikasiCekCuaca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AplikasiCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(203, 220, 235));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Masukkan Nama Kota:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        cbmbxFavorit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAtau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtau.setText("Atau");

        btnCekCuaca.setBackground(new java.awt.Color(99, 163, 97));
        btnCekCuaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCekCuaca.setForeground(new java.awt.Color(255, 255, 255));
        btnCekCuaca.setText("Cek Cuaca");
        btnCekCuaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekCuacaActionPerformed(evt);
            }
        });

        btnTambahFavorit.setBackground(new java.awt.Color(248, 123, 27));
        btnTambahFavorit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahFavorit.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahFavorit.setText("Tambah Favorit");

        btnHapusFavorit.setBackground(new java.awt.Color(205, 44, 88));
        btnHapusFavorit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusFavorit.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusFavorit.setText("Hapus Favorit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCekCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambahFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapusFavorit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAtau)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbmbxFavorit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbmbxFavorit)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAtau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahFavorit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusFavorit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(140, 205, 235));

        lblInformasiCuaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInformasiCuaca.setText("Informasi Cuaca");

        lblNamaKota.setText("Jakarta, Indonesia");

        lblSuhu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSuhu.setText("28° C");

        lblKondisiCuaca.setText("Cerah Berawan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInformasiCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblKondisiCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNamaKota)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(lblSuhu))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformasiCuaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(lblNamaKota, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblKondisiCuaca, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtKelembapan.setText("Kelembapan:");

        txtKecepatanAngin.setText("Kec. Angin:");

        txtTekanan.setText("Tekanan:");

        lblRiwayatPencarian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRiwayatPencarian.setText("Riwayat Pencarian:");

        tblCuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kota", "Suhu", "Kondisi", "Waktu"
            }
        ));
        jScrollPane1.setViewportView(tblCuaca);

        btnSimpan.setBackground(new java.awt.Color(84, 89, 172));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan ke CSV");

        btnMuatData.setBackground(new java.awt.Color(121, 101, 193));
        btnMuatData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMuatData.setForeground(new java.awt.Color(255, 255, 255));
        btnMuatData.setText("Muat Data");

        btnHapus.setBackground(new java.awt.Color(221, 168, 83));
        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Riwayat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRiwayatPencarian)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMuatData, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKecepatanAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTekanan)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtKelembapan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKecepatanAngin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTekanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRiwayatPencarian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMuatData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(225, 225, 225))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekCuacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekCuacaActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_btnCekCuacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) { }
        java.awt.EventQueue.invokeLater(() -> new WeatherAppGUI().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AplikasiCekCuaca;
    private javax.swing.JButton btnCekCuaca;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapusFavorit;
    private javax.swing.JButton btnMuatData;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahFavorit;
    private javax.swing.JComboBox<String> cbmbxFavorit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtau;
    private javax.swing.JLabel lblInformasiCuaca;
    private javax.swing.JLabel lblKondisiCuaca;
    private javax.swing.JLabel lblNamaKota;
    private javax.swing.JLabel lblRiwayatPencarian;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JTable tblCuaca;
    private javax.swing.JTextField txtKecepatanAngin;
    private javax.swing.JTextField txtKelembapan;
    private javax.swing.JTextField txtNamaKota;
    private javax.swing.JTextField txtTekanan;
    // End of variables declaration//GEN-END:variables

    private void cekCuaca(String kota) {
        new SwingWorker<WeatherAPI.WeatherData, Void>() {
            @Override
            protected WeatherAPI.WeatherData doInBackground() throws Exception {
                return WeatherAPI.getWeather(kota);
            }

            @Override
            protected void done() {
                try {
                    WeatherAPI.WeatherData w = get();

                    // 1) Header Informasi
                    lblNamaKota.setText(w.getKotaNegara()); // contoh: Jakarta, ID (atau Indonesia jika mau kamu mapping)
                    lblSuhu.setText(String.format("%.0f°C", w.getSuhu()));
                    lblKondisiCuaca.setText(w.getKondisi());

                    // 2) Ikon cuaca (pakai ikon resmi OpenWeather)
                    try {
                        String iconUrl = "https://openweathermap.org/img/wn/" + w.getIconCode() + "@2x.png";
                        ImageIcon raw = new ImageIcon(new URL(iconUrl));
                        Image scaled = raw.getImage().getScaledInstance(90, 90, Image.SCALE_SMOOTH);
                        lblNamaKota.setIcon(new ImageIcon(scaled)); // ikon di atas, teks kota di bawah
                    } catch (Exception ignore) {
                        lblNamaKota.setIcon(null);
                    }

                    // 3) Badge Kelembapan / Angin / Tekanan
                    txtKelembapan.setText("Kelembapan: " + w.getKelembapan() + "%");
                    txtKecepatanAngin.setText(String.format("Kec. Angin: %.0f km/h", w.getAnginKMH()));
                    txtTekanan.setText("Tekanan: " + w.getTekanan() + " mb");

                    // 4) Tambah ke tabel riwayat (format waktu HH:mm)
                    String waktu = java.time.LocalTime.now().withNano(0).toString(); // HH:mm:ss
                    waktu = waktu.length() >= 5 ? waktu.substring(0,5) : waktu;
                    model.addRow(new Object[]{
                        w.getKotaNegara(),
                        String.format("%.0f°C", w.getSuhu()),
                        w.getKondisi(),
                        waktu
                    });

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(WeatherAppGUI.this,
                            "Gagal mengambil data cuaca.\n" + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }.execute();
    }
    
    private void simpanCSV() {
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk disimpan.");
            return;
        }
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new File("riwayat_cuaca.csv"));
        int ret = chooser.showSaveDialog(this);
        if (ret != JFileChooser.APPROVE_OPTION) return;

        File f = chooser.getSelectedFile();
        try (PrintWriter pw = new PrintWriter(new FileWriter(f))) {
            pw.println("Kota,Suhu,Kondisi,Waktu");
            for (int i = 0; i < model.getRowCount(); i++) {
                pw.println(
                    escapeCSV(model.getValueAt(i, 0)) + "," +
                    escapeCSV(model.getValueAt(i, 1)) + "," +
                    escapeCSV(model.getValueAt(i, 2)) + "," +
                    escapeCSV(model.getValueAt(i, 3))
                );
            }
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke: " + f.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan file CSV: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void muatCSV() {
        JFileChooser chooser = new JFileChooser();
        int ret = chooser.showOpenDialog(this);
        if (ret != JFileChooser.APPROVE_OPTION) return;

        File f = chooser.getSelectedFile();
        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            model.setRowCount(0);
            String line;
            boolean first = true;
            while ((line = br.readLine()) != null) {
                if (first) { first = false; if (line.toLowerCase().startsWith("kota,")) continue; }
                String[] p = line.split(",", -1);
                if (p.length >= 4) model.addRow(new Object[]{p[0], p[1], p[2], p[3]});
            }
            JOptionPane.showMessageDialog(this, "Data berhasil dimuat dari: " + f.getAbsolutePath());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat file CSV: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String escapeCSV(Object o) {
        if (o == null) return "";
        String s = o.toString();
        if (s.contains(",") || s.contains("\"") || s.contains("\n")) {
            s = s.replace("\"", "\"\"");
            return "\"" + s + "\"";
        }
        return s;
    }
}